### ISSUE TITLE
Create 'version' tags in repo for referencing

### ISSUE THREAD

**Issue by miketheman** [dbridges/cocoa-tlassemble#2]
Hi @dbridges,

I've submitted a pull to Homebrew to build/install this as a package, and in order to do so, they require a version reference, instead of pulling always from `master` branch.

This should be pretty straightforward, such as adding a tag to the repo at the released reference - such as `1.0` or `v1.0` or the like.

Would appreciate it so that others may benefit from the tool you've written and makes installation a breeze. :)

Thanks!

ref: mxcl/homebrew#21817

**Comment by dbridges** [comment]
v1.0 tag added.
