### ISSUE TITLE
Not in homebrew due to use of obsolete QTKit framework

### ISSUE THREAD

**Issue by Frizlab** [dbridges/cocoa-tlassemble#4]
You are not in homebrew anymore (to be precise you’ve been moved to the boneyard) because you use the obsolete QTKit framework.
Would you care for a small modernisation? :)

**Comment by surak** [comment]
This fork has updated to a newer framework, and it works with Mojave, as of June 2019: https://github.com/wadetregaskis/cocoa-tlassemble

**Comment by Frizlab** [comment]
Good to know. Thanks.
